// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using InsuranceService.Web;
using Microsoft.AspNetCore.Hosting;

[TestFixture]
public class InsuranceServiceWebTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
    private IWebHost _webHost;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void boundaryrural17() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("17");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("rural");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Error: Invalid age or location"));
  }
  [Test]
  public void boundaryrural30() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("30");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("rural");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 5€"));
  }
  [Test]
  public void boundaryrural50() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("50");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("rural");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 2.125€"));
  }
  [Test]
  public void boundaryurban17() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("17");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Error: Invalid age or location"));
  }
  [Test]
  public void boundaryurban18() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("18");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 6€"));
  }
  [Test]
  public void boundaryurban35() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("35");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 6€"));
  }
  [Test]
  public void boundaryurban36() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("36");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 5€"));
  }
  [Test]
  public void boundaryurban49() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("49");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector("form")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 5€"));
  }
  [Test]
  public void boundaryurban50() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("50");
    {
      var element = driver.FindElement(By.Id("location"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("form"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector("form")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 4.25€"));
  }
  [Test]
  public void invalidcat42() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("42");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("cat");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Error: Invalid age or location"));
  }
  [Test]
  public void invalidrural16() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("16");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("rural");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Error: Invalid age or location"));
  }
  [Test]
  public void reprruban42() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("42");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 5€"));
  }
  [Test]
  public void invalidurban5() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("5");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Error: Invalid age or location"));
  }
  [Test]
  public void reprrural24() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("24");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("rural");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 5€"));
  }
  [Test]
  public void reprrural42() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("42");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("rural");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 2.5€"));
  }
  [Test]
  public void reprrural60() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("60");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("rural");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 2.125€"));
  }
  [Test]
  public void reprubran24() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("24");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 6€"));
  }
  [Test]
  public void reprurban60() {
    driver.Navigate().GoToUrl("http://localhost:5126/CalcPremium");
    driver.Manage().Window.Size = new System.Drawing.Size(1024, 714);
    driver.FindElement(By.Id("age")).Click();
    driver.FindElement(By.Id("age")).SendKeys("60");
    driver.FindElement(By.Id("location")).Click();
    driver.FindElement(By.Id("location")).SendKeys("urban");
    driver.FindElement(By.CssSelector(".btn")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".alert")).Text, Is.EqualTo("Premium: 4.25€"));
  }
}
